export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FETCH_MENUS = "FETCH_MENUS";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const FILTER_MENUS = "FILTER_MENUS";
export const UPDATE_SORT = "UPDATE_SORT";
export const UPDATE_GRID_VIEW = "UPDATE_GRID_VIEW";
export const UPDATE_LIST_VIEW = "UPDATE_LIST_VIEW";
