export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const SET_MENU_DATA = "SET_MENU_DATA";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const FILTER_MENUS = "FILTER_MENUS";
