export const FETCH_MENUS = "FETCH_MENUS"; // fetch all menus on initial load.
export const UPDATE_FILTERS = "UPDATE_FILTERS"; // sets filtering condition in state.
export const FILTER_MENUS = "FILTER_MENUS"; // filters the menu item based on the state.filters conditions.
export const UPDATE_SORT = "UPDATE_SORT"; // sets the sorting condition in the state
export const SORT_MENU = "SORT_MENU"; // sorts the menu item based on the state.sort condition.
export const UPDATE_GRID_VIEW = "UPDATE_GRID_VIEW"; // sets the grid view for menu items in menus page.
export const UPDATE_LIST_VIEW = "UPDATE_LIST_VIEW"; // sets the list view for menu items in menus page.
export const GET_CATEGORIES = "GET_CATEGORIES"; // get the unique categories from state.menus on initial load.
export const UPDATE_MIN_MAX_PRICES = "UPDATE_MIN_MAX_PRICES"; // sets min and max prices to the state.filters as defaults.
